name: Build and Push Docker Image
on:
  push:
    branches:
      - "devlopment"
  pull_request:
    branches:
      - "devlopment"

jobs:
  Build_Push:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: v1.0.${{ github.run_number }}
      IMAGE_NAME: "${{ env.DOCKER_USERNAME }}/${{ env.APP_NAME }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
          docker build -t ${{ env.IMAGE_NAME }}:latest .

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.IMAGE_NAME }}:latest